<#function getRuntime(root)>
  <#if root.TIME_DOMAIN??>
    <#return root.TIME_DOMAIN[0]>
  </#if>
</#function>
{
   "format":"image/gif",
   "group":"${WORKSPACE}",<#-- FIXED -->
   "name":"${LAYERNAME}",<#-- FIXED -->
   "opacity":1.0,
   "selected":false,
   "source":"${WORKSPACE}", <#-- FIXED -->
   "styles":["${DEFAULT_STYLE}"],
   "title":"${LAYERNAME}", <#-- FIXED -->
   "transparent":true,
   <#if GN_UUID??>"uuid":"${GN_UUID}",</#if><#-- UUID from GeoNetwork -->
   "visibility":false,
   "ratio":1,
   "srs":"EPSG:900913",
   "transitionEffect":"resize"
   <#if ELEVATION_DOMAIN??>,"elevation":"${ELEVATION_DOMAIN[0]}"</#if><#-- FIXED -->
},{
   "format":"image/png",
   "group": "Limiti Mondiali",
   "name":"confini_mondiali_stati",
   "selected":false,                   
   "source":"LaMMA_confini", 
   "styles":["confini"],
   "style":["confini"],
   "title":"Stati",
   "transparent":true,
   "visibility":true,
   "ratio":1,
   "srs":"EPSG:900913",
   "queryable": false,
   "displayInLayerSwitcher": true,
},{
   "format":"image/png",
   "group": "Limiti Mondiali",
   "name":"confini_mondiali_regioni",
   "selected":false,                   
   "source":"LaMMA_confini", 
   "styles":["confini"],
   "style":["confini"],
   "title":"Regioni",
   "transparent":true,
   "visibility":true,
   "ratio":1,
   "srs":"EPSG:900913",
   "queryable": false,
   "displayInLayerSwitcher": true,
},{
   "format":"image/png",
   "group": "Limiti Mondiali",
   "name":"confini_mondiali_provincie",
   "selected":false,                   
   "source":"LaMMA_confini", 
   "styles":["confini"],
   "style":["confini"],
   "title":"Province",
   "transparent":true,
   "visibility":false,
   "ratio":1,
   "srs":"EPSG:900913",
   "queryable": false,
   "displayInLayerSwitcher": true,
},{
   "format":"image/png",
   "group": "Limiti Mondiali",
   "name":"comuni",
   "selected":false,                   
   "source":"LaMMA_confini", 
   "styles":["confini"],
   "style":["confini"],
   "title":"Comuni Italia",
   "transparent":true,
   "visibility":false,
   "ratio":1,
   "srs":"EPSG:900913",
   "queryable": false,
   "displayInLayerSwitcher": true,
},{
   "format":"image/png8",
   "group":"Stazioni",
   "name":"prec60_l",
   "opacity":0.9,
   "buffer": 2,
   "selected":false,
   "tiled":false,
   "source":"LaMMA_Stazioni", 
   "styles":["heatmap_pioggia"],
   "style":["pioggia"],
   "title":"Pioggia oraria",
   "transparent":true,
   "visibility":false,
   "ratio":1,
   "srs":"EPSG:900913",
   "getGraph": true,
   "graphTable": "prec60_l",
   "graphAttribute": "prec_mm",
   "cumulative": true,                        
   "elevation":"0.0"
},{
   "format":"image/png8",
   "group":"Stazioni",
   "name":"prec360_l",
   "opacity":0.9,
   "selected":false,
   "tiled":false,                       
   "source":"LaMMA_Stazioni", 
   "styles":["heatmap_pioggia"],
   "style":["pioggia"],
   "title":"Pioggia 6 ore",
   "transparent":true,
   "visibility":false,
   "ratio":1,
   "srs":"EPSG:900913",
   "getGraph": true,
   "graphTable": "prec360_l",
   "graphAttribute": "prec_mm",
   "cumulative": true, 
   "elevation":"0.0"
},{
   "format":"image/png8",
   "group":"Stazioni",
   "name":"temparia_l",
   "opacity":0.9,
   "selected":false,
   "tiled":false,                       
   "source":"LaMMA_Stazioni", 
   "styles":["temperatura"],
   "style":["temperatura_legend"],
   "title":"Temperatura oraria",
   "transparent":true,
   "visibility":true,
   "ratio":1,
   "srs":"EPSG:900913",
   "getGraph": true,
   "graphTable": "temparia_l",
   "graphAttribute": "temp_c",
   "cumulative": false,                        
   "elevation":"0.0"
},{
   "format":"image/png8",
   "group":"Stazioni",
   "name":"umid_l",
   "opacity":0.9,
   "selected":false,
   "tiled":false,                       
   "source":"LaMMA_Stazioni", 
   "styles":["umidita"],
   "style":["umidita"],
   "title":"Umidita oraria",
   "transparent":true,
   "visibility":false,
   "ratio":1,
   "srs":"EPSG:900913",
   "getGraph": true,
   "graphTable": "umid_l",
   "graphAttribute": "umid_per",                       
   "elevation":"0.0"
},{
   "format":"image/png8",
   "group":"Stazioni",
   "name":"umid_l",
   "opacity":0.9,
   "selected":false,
   "tiled":false,                       
   "source":"LaMMA_Stazioni", 
   "styles":["temp_rugiada_legend"],
   "style":["temp_rugiada_legend"],
   "title":"Temp rugiada oraria",
   "transparent":true,
   "visibility":false,
   "ratio":1,
   "srs":"EPSG:900913",
   "getGraph": true,
   "graphTable": "umid_l",
   "graphAttribute": "trug_c",                       
   "elevation":"0.0"
},{
   "format":"image/png8",
   "group":"Stazioni",
   "name":"vent_l",
   "opacity":0.9,
   "selected":false,
   "tiled":false,                       
   "source":"LaMMA_Stazioni", 
   "styles":["vento"],
   "style":["vento"],
   "title":"Vento",
   "transparent":true,
   "visibility":false,
   "ratio":1,
   "srs":"EPSG:900913",
   "getGraph": true,
   "graphTable": "vent_l",
   "graphAttribute": "vven_ms",
   "elevation":"0.0"
}       